-- Alimentação da equipe (jantas dos funcionários) — Controle de Produção › aba Alimentação.
-- Diferente da execução de produção: NÃO tem ficha técnica, rendimento nem peso mestre.
-- A pessoa seleciona insumos direto (arroz, feijão, linguiça...), informa a quantidade,
-- o preço vem do catálogo (silver.insumo_catalogo) e registramos a refeição do dia + o tempo.
-- Modela um par execução/insumo próprio (producao_execucao exige producao_id NOT NULL).

create table if not exists operations.alimentacao_execucao (
  id              bigint generated by default as identity primary key,
  bar_id          integer     not null,
  responsavel_id  integer,
  responsavel_nome text,
  data_refeicao   date        not null,
  tipo            text        not null default 'janta',   -- almoco | janta | ceia
  num_pessoas     integer,                                -- opcional: nº de refeições servidas (custo por pessoa)
  inicio          timestamptz,
  fim             timestamptz,
  duracao_seg     integer,
  custo_total     numeric,
  observacao      text,
  criado_por      text,
  criado_em       timestamptz not null default now()
);

create table if not exists operations.alimentacao_insumo (
  id                bigint generated by default as identity primary key,
  execucao_id       bigint  not null references operations.alimentacao_execucao(id) on delete cascade,
  insumo_codigo     text,
  insumo_id_vmarket bigint,
  nome              text,
  qtd               numeric,
  unidade           text,
  preco_un          numeric,
  custo             numeric
);

create index if not exists idx_alimentacao_execucao_bar_data
  on operations.alimentacao_execucao (bar_id, data_refeicao desc);
create index if not exists idx_alimentacao_insumo_execucao
  on operations.alimentacao_insumo (execucao_id);

-- Mesmo modelo de segurança das tabelas de execução: RLS on, acesso só via service_role
-- (a API usa o admin client / service role; PostgREST anon/authenticated não enxerga operations).
alter table operations.alimentacao_execucao enable row level security;
alter table operations.alimentacao_insumo   enable row level security;

grant select, insert, update, delete on operations.alimentacao_execucao to service_role;
grant select, insert, update, delete on operations.alimentacao_insumo   to service_role;

comment on table operations.alimentacao_execucao is
  'Refeições da equipe (jantas). Seleção direta de insumos, sem ficha/rendimento. Controle de Produção › Alimentação.';
