-- Fix logica de atrasao/atrasinho com regra historica por bar + data
-- ============================================================================
-- Regras (confirmadas com socio):
-- Bar 3 (Ordinario):
--   - Cozinha: sempre t0_t2 (preparo)
--   - Bar:     sempre t0_t3 (entrega)
-- Bar 4 (Deboche) - mudou processo em 2026-03:
--   - Cozinha: t0_t2 ate 19/03/2026, t0_t3 a partir de 20/03/2026
--   - Bar:     t0_t2 ate 06/03/2026, t0_t3 a partir de 07/03/2026
--
-- Thresholds (em segundos):
--   - Atrasao cozinha: > 1200 (>20min)   |  Atrasinho cozinha: 900-1200 (15-20min)
--   - Atrasao bar:     > 600  (>10min)   |  Atrasinho bar:     300-600  (5-10min)
--
-- Bug anterior em calculate_evento_metrics: thresholds estavam em MINUTOS
-- (> 20, > 10) sendo comparados com t0_t2/t0_t3 em SEGUNDOS - pegava virtualmente tudo.
-- ============================================================================

-- Funcoes completas em producao via execute_sql, esta migration documenta as regras.
-- Para recriar:
-- 1. public.calculate_evento_metrics(evento_id integer) - versao_calculo = 27
-- 2. public.etl_gold_desempenho_mensal(p_bar_id, p_ano, p_mes) - versao_etl = 10
--
-- Convencao dos cutoffs internos no ETL:
--   v_cut_coz / v_cut_bar = data onde a unidade muda de t0_t2 -> t0_t3
--   Logica por linha: CASE WHEN data_producao >= v_cut THEN t0_t3 ELSE t0_t2 END
--   '1900-01-01' = sempre usa t0_t3 (cutoff no passado)
--   '9999-12-31' = nunca usa t0_t3 (sempre t0_t2)
