-- ============================================================================
-- Multi-dia no Planejamento da Produção (pedido Isaias/Deboche 06/07).
-- Antes: producao_plano_item tinha 1 dia_producao (text) e 1 decidido_receitas
-- por produção/semana. Agora a mesma produção pode ser marcada em VÁRIOS dias,
-- cada dia com sua própria quantidade (ex.: pastel Seg 2 / Ter 3 / Qui 2).
-- O item-pai (producao_plano_item) segue como o TOTAL da semana (= soma dos dias);
-- esta tabela guarda a distribuição por dia. dia é text (ISO 'YYYY-MM-DD'),
-- mesma convenção de producao_plano_item.dia_producao.
-- ============================================================================
create table if not exists operations.producao_plano_item_dia (
  id bigint generated by default as identity primary key,
  plano_id bigint not null references operations.producao_plano(id) on delete cascade,
  producao_id bigint not null,
  dia text not null,
  decidido_receitas numeric not null default 0,
  decidido_qtd numeric not null default 0,
  atualizado_em timestamptz not null default now(),
  unique (plano_id, producao_id, dia)
);
create index if not exists idx_ppid_plano on operations.producao_plano_item_dia(plano_id);
create index if not exists idx_ppid_plano_dia on operations.producao_plano_item_dia(plano_id, dia);

grant select, insert, update, delete on operations.producao_plano_item_dia to service_role;
notify pgrst, 'reload schema';
