-- View: eventos
-- Alias para eventos_base
-- Mantido para compatibilidade com código legado

CREATE OR REPLACE VIEW public.eventos AS
SELECT id,
    data_evento,
    dia_semana,
    semana,
    nome,
    artista,
    genero,
    bar_id,
    ativo,
    m1_r,
    cl_plan,
    res_p,
    lot_max,
    te_plan,
    tb_plan,
    c_artistico_plan,
    criado_em,
    atualizado_em,
    real_r,
    cl_real,
    res_tot,
    te_real,
    tb_real,
    t_medio,
    c_art,
    c_prod,
    percent_art_fat,
    percent_b,
    percent_d,
    percent_c,
    t_coz,
    t_bar,
    fat_19h,
    observacoes,
    fat_19h_percent,
    sympla_liquido,
    sympla_checkins,
    yuzer_liquido,
    yuzer_ingressos,
    calculado_em,
    precisa_recalculo,
    versao_calculo,
    faturamento_couvert_manual,
    faturamento_bar_manual,
    faturamento_couvert,
    faturamento_bar,
    te_real_calculado,
    tb_real_calculado,
    nome_evento,
    publico_real,
    faturamento_liquido,
    capacidade_estimada
FROM eventos_base;
