-- View: tempo
-- Alias para contahub_tempo
-- Dados de tempo de produção de pedidos

CREATE OR REPLACE VIEW public.tempo AS
SELECT id,
    grp_desc,
    prd_desc,
    vd_mesadesc,
    vd_localizacao,
    itm,
    t0_lancamento,
    t1_prodini,
    t2_prodfim,
    t3_entrega,
    t0_t1,
    t0_t2,
    t0_t3,
    t1_t2,
    t1_t3,
    t2_t3,
    prd,
    prd_idexterno,
    loc_desc,
    usr_abriu,
    usr_lancou,
    usr_produziu,
    usr_entregou,
    usr_transfcancelou,
    prefixo,
    tipovenda,
    ano,
    mes,
    dia,
    dds,
    diadasemana,
    hora,
    itm_qtd,
    bar_id,
    data,
    created_at,
    updated_at,
    categoria,
    idempotency_key
FROM contahub_tempo;
