-- Função: get_dia_semana
CREATE OR REPLACE FUNCTION public.get_dia_semana(d date) RETURNS text LANGUAGE plpgsql SET search_path TO 'public'
AS $$
BEGIN RETURN CASE EXTRACT(DOW FROM d) WHEN 0 THEN 'DOMINGO' WHEN 1 THEN 'SEGUNDA' WHEN 2 THEN 'TERÇA' WHEN 3 THEN 'QUARTA' WHEN 4 THEN 'QUINTA' WHEN 5 THEN 'SEXTA' WHEN 6 THEN 'SÁBADO' END; END;
$$;
